In [2]:
import pandas as pd
from pathlib import Path
from datetime import timedelta
import numpy as np

from bokeh.models import ColumnDataSource, LabelSet
from bokeh.plotting import figure, show

In [3]:
root_folder = Path.cwd().parents[1]

df = pd.read_csv(root_folder/'data/processed'/'01-final.csv')

In [5]:
df.head()

,PST,Tide,Height,Deg,Period,Wind Speed,Wind Direction,Ideal Wind,Ideal Period,Ideal Tide,Ideal Swell,Score
0,2017-01-01 07:00:00-08:00,3.82,2.47,306.0,11.0,7.0,260,0,1,1,0,2
1,2017-01-01 08:00:00-08:00,4.42,2.37,309.0,9.0,6.0,40,1,1,1,0,3
2,2017-01-01 09:00:00-08:00,5.13,2.38,310.0,11.0,0.0,calm,1,1,0,0,2
3,2017-01-01 10:00:00-08:00,5.66,2.66,314.0,11.0,0.0,calm,1,1,0,0,2
4,2017-01-01 11:00:00-08:00,5.71,2.38,303.0,11.0,5.0,150,1,1,0,1,3

In [4]:
df['UTC'] = pd.to_datetime(df['PST'], utc=True)

df['PSTdt'] = df['UTC']-timedelta(hours=8)

In [10]:
df.head()

,PST,Tide,Height,Deg,Period,Wind Speed,Wind Direction,Ideal Wind,Ideal Period,Ideal Tide,Ideal Swell,Score,UTC,PSTdt
0,2017-01-01 07:00:00-08:00,3.82,2.47,306.0,11.0,7.0,260,0,1,1,0,2,2017-01-01 15:00:00+00:00,2017-01-01 07:00:00+00:00
1,2017-01-01 08:00:00-08:00,4.42,2.37,309.0,9.0,6.0,40,1,1,1,0,3,2017-01-01 16:00:00+00:00,2017-01-01 08:00:00+00:00
2,2017-01-01 09:00:00-08:00,5.13,2.38,310.0,11.0,0.0,calm,1,1,0,0,2,2017-01-01 17:00:00+00:00,2017-01-01 09:00:00+00:00
3,2017-01-01 10:00:00-08:00,5.66,2.66,314.0,11.0,0.0,calm,1,1,0,0,2,2017-01-01 18:00:00+00:00,2017-01-01 10:00:00+00:00
4,2017-01-01 11:00:00-08:00,5.71,2.38,303.0,11.0,5.0,150,1,1,0,1,3,2017-01-01 19:00:00+00:00,2017-01-01 11:00:00+00:00

In [5]:
df17 = df[df.PSTdt.dt.year == 2017]

In [43]:
df17['count'] = np.ones(len(df17),dtype=int)

C:\Users\audre\AppData\Local\Temp\ipykernel_15952\3382844535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df17['count'] = np.ones(len(df17),dtype=int)

In [31]:
df17.groupby([df17['PSTdt'].dt.month]).sum()

C:\Users\audre\AppData\Local\Temp\ipykernel_15952\433549555.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df17.groupby([df17['PSTdt'].dt.month]).sum()

,Tide,Height,Deg,Period,Wind Speed,Ideal Wind,Ideal Period,Ideal Tide,Ideal Swell,Score,count
PSTdt,,,,,,,,,,,
1,988.91,906.12,96532.0,3656.0,2000.0,155,243,180,176,754,341
2,856.31,838.71,93171.0,3100.0,2375.5,122,207,162,219,710,332
3,957.74,884.70,113186.0,3098.0,2657.5,161,179,201,208,749,401
4,963.92,1094.65,119144.0,3864.0,3339.0,117,256,241,212,826,417
5,1197.61,1047.23,134727.0,3977.0,3507.5,125,286,293,128,832,465
6,1321.92,918.99,125685.0,3170.0,3226.0,113,174,309,156,752,450
7,1471.43,817.65,126580.0,3175.0,2986.0,154,146,344,57,701,465
8,1559.25,667.18,115862.0,3178.0,2930.0,144,184,353,48,729,450
9,1401.81,616.04,107854.0,3012.0,2793.5,110,206,286,79,681,390
10,1364.25,898.02,108529.0,3761.0,2215.5,154,272,254,123,803,379
11,1106.83,603.63,95358.0,3305.0,1994.5,151,239,190,137,717,338
12,1032.62,678.89,99510.0,3766.0,1525.0,191,274,168,220,853,341

Need to make an automatic position assignment thing for each hour based on both score and time.....will just do it by score and build bars up since location of new score section depends on height of previous bar.

In [32]:
df17[df17['Score']==0]

,PST,Tide,Height,Deg,Period,Wind Speed,Wind Direction,Ideal Wind,Ideal Period,Ideal Tide,Ideal Swell,Score,UTC,PSTdt,count
60,2017-01-06 12:00:00-08:00,1.87,1.26,216.0,4.0,6.0,170,0,0,0,0,0,2017-01-06 20:00:00+00:00,2017-01-06 12:00:00+00:00,1
69,2017-01-07 10:00:00-08:00,1.71,2.15,110.0,4.0,6.0,70,0,0,0,0,0,2017-01-07 18:00:00+00:00,2017-01-07 10:00:00+00:00,1
70,2017-01-07 11:00:00-08:00,1.07,2.16,113.0,4.0,6.0,60,0,0,0,0,0,2017-01-07 19:00:00+00:00,2017-01-07 11:00:00+00:00,1
71,2017-01-07 12:00:00-08:00,0.95,1.92,113.0,4.0,7.0,140,0,0,0,0,0,2017-01-07 20:00:00+00:00,2017-01-07 12:00:00+00:00,1
72,2017-01-07 13:00:00-08:00,0.63,1.84,115.0,4.0,6.0,140,0,0,0,0,0,2017-01-07 21:00:00+00:00,2017-01-07 13:00:00+00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4475,2017-12-05 10:00:00-08:00,7.05,1.88,305.0,4.0,13.0,280,0,0,0,0,0,2017-12-05 18:00:00+00:00,2017-12-05 10:00:00+00:00,1
4480,2017-12-05 15:00:00-08:00,0.38,1.77,314.0,7.0,9.0,270,0,0,0,0,0,2017-12-05 23:00:00+00:00,2017-12-05 15:00:00+00:00,1
4623,2017-12-18 15:00:00-08:00,-0.04,1.31,306.0,7.0,7.0,240,0,0,0,0,0,2017-12-18 23:00:00+00:00,2017-12-18 15:00:00+00:00,1
4646,2017-12-20 16:00:00-08:00,0.29,2.83,314.0,7.0,16.0,260,0,0,0,0,0,2017-12-21 00:00:00+00:00,2017-12-20 16:00:00+00:00,1
4647,2017-12-20 17:00:00-08:00,-0.34,2.67,307.0,4.0,10.0,320,0,0,0,0,0,2017-12-21 01:00:00+00:00,2017-12-20 17:00:00+00:00,1

x coordinates will repeat $[1,2,3,4,5,6]$ and y coordinates will repeat $[1,1,1,1,1,1]$, $[2,2,2,2,2,2]$, etc

In [33]:
291/6

48.5

In [34]:
x = 48*[1,2,3,4,5,6]

In [35]:
x.extend([1,2,3])
len(x)

291

In [36]:
y=[]
for n in range(48):
    l = 6*[n]
    y.extend(l)
y.extend([48,48,48])
len(y)

291

In [49]:
zero = df17[df17['Score']==0]

In [13]:
df17['Month'] = df17['PSTdt'].dt.month

C:\Users\audre\AppData\Local\Temp\ipykernel_17828\903891862.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df17['Month'] = df17['PSTdt'].dt.month

In [19]:
sorted = df17.sort_values(by=['Month','Score', 'PSTdt'], axis = 0)

In [20]:
sorted[sorted['PSTdt'].dt.month==1]

,PST,Tide,Height,Deg,Period,Wind Speed,Wind Direction,Ideal Wind,Ideal Period,Ideal Tide,Ideal Swell,Score,UTC,PSTdt,Month
60,2017-01-06 12:00:00-08:00,1.87,1.26,216.0,4.0,6.0,170,0,0,0,0,0,2017-01-06 20:00:00+00:00,2017-01-06 12:00:00+00:00,1
69,2017-01-07 10:00:00-08:00,1.71,2.15,110.0,4.0,6.0,70,0,0,0,0,0,2017-01-07 18:00:00+00:00,2017-01-07 10:00:00+00:00,1
70,2017-01-07 11:00:00-08:00,1.07,2.16,113.0,4.0,6.0,60,0,0,0,0,0,2017-01-07 19:00:00+00:00,2017-01-07 11:00:00+00:00,1
71,2017-01-07 12:00:00-08:00,0.95,1.92,113.0,4.0,7.0,140,0,0,0,0,0,2017-01-07 20:00:00+00:00,2017-01-07 12:00:00+00:00,1
72,2017-01-07 13:00:00-08:00,0.63,1.84,115.0,4.0,6.0,140,0,0,0,0,0,2017-01-07 21:00:00+00:00,2017-01-07 13:00:00+00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,2017-01-30 14:00:00-08:00,2.50,1.73,290.0,13.0,3.0,250,1,1,1,1,4,2017-01-30 22:00:00+00:00,2017-01-30 14:00:00+00:00,1
330,2017-01-31 07:00:00-08:00,2.43,1.49,286.0,13.0,0.0,calm,1,1,1,1,4,2017-01-31 15:00:00+00:00,2017-01-31 07:00:00+00:00,1
331,2017-01-31 08:00:00-08:00,3.14,1.28,290.0,13.0,0.0,calm,1,1,1,1,4,2017-01-31 16:00:00+00:00,2017-01-31 08:00:00+00:00,1
332,2017-01-31 09:00:00-08:00,4.04,1.50,286.0,13.0,0.0,calm,1,1,1,1,4,2017-01-31 17:00:00+00:00,2017-01-31 09:00:00+00:00,1
333,2017-01-31 10:00:00-08:00,4.68,1.60,292.0,15.0,0.0,calm,1,1,1,1,4,2017-01-31 18:00:00+00:00,2017-01-31 10:00:00+00:00,1